packages:
  - '.'

allowBuilds:
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@trigger.dev/core@4.5.9'
  - '@trigger.dev/sdk@4.5.9'
  - '@vitejs/plugin-react@6.0.5'
  - '@playwright/test@1.62.1'
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'
  - playwright-core@1.62.1
  - playwright@1.62.1
  - tldts-core@7.4.10
  - tldts@7.4.10
  - opik@2.2.17
